create: fail on invalid value of --type
Now we write:

	Error: invalid argument "mytype" for "-t, --type" flag: must be one of "plain", or "totp"

Instead of silently corrupting the database.